#!/bin/bash

# This file processes either *-mindisres.xvg (absolute minimum throughout trajectory; that is, no -respertime option),
# or mindisres_ave.dat (generated by mindisres_ave.awk)
# and prints out a list of residue numbers that ever come within cutoff distance from the probe throughout the trajectory (for *-mindisres.xvg)
# or a list of residues whose average minimum distance comes within cutoff from the probe (for mindisres_ave.awk)

read -p "input file name: " xvg
read -p "cutoff (in exact same units as the values to be compared): " cutoff
read -p "line number of first data entry (that is, if the .xvg heading has 23 lines, then enter 24 here. Enter 1 for mindisres_ave.dat or mindisres_percent.dat): " first
read -p "larger than cutoff or smaller than cutoff? (0: smaller; 1: larger) " ioperant

awk -v xvg=$xvg -v cutoff=$cutoff -v first=$first -v ioperant=$ioperant 'BEGIN{}

NR>=first{
	if (ioperant==0){	
		if ( $2 < cutoff ) {
			print $1, $2
		}
	}
	if (ioperant==1){	
		if ( $2 > cutoff ) {
			print $1, $2
		}
	}
}

END{}' $xvg | sort -k 2